---

  - name: Ensure Redis is installed.
    apt:
      name: "redis-server"
      state: present

  - name: modify redis port config
    template:
      src: redis.conf.j2
      dest: /etc/redis/redis.conf
      mode: 0644
    notify: restart redis

