---

#  - name: download nginx install packages
#    get_url:
#      url: "{{apache_url}}/nginx/{{ item }}"
#      dest: "{{nginx_src_dir}}"

#    with_items:
#      - headers-more-nginx-module-{{header_version}}.tar.gz
#      - nginx-{{nginx_version}}.tar.gz
#      - openssl-{{openssl_version}}.tar.gz
#      - pcre-{{pcre_version}}.tar.gz
#      - zlib-{{zlib_version}}.tar.gz

  - name: unarchive install packages
    unarchive:
      #src: "{{nginx_src_dir}}/{{ item.name }}-{{item.version}}.tar.gz"
      src: "{{ item.name }}-{{item.version}}.tar.gz"
      dest: "{{nginx_src_dir}}"
      #remote_src: True
    with_items:
      - { name: 'headers-more-nginx-module', version: '{{header_version}}'}
      - { name: 'nginx',version: '{{nginx_version}}'}
      - { name: 'openssl',version: '{{openssl_version}}'}
      - { name: 'pcre',version: '{{pcre_version}}'}
      - { name: 'zlib',version: '{{zlib_version}}'}

  - name: install pcre
    shell: "cd {{nginx_src_dir}}/pcre-{{pcre_version}} && ./configure && make && make install"

  - name: install zlib
    apt:
      name: zlib1g-dev
      state: present
#  - name: install zlib,scp install_zlib.sh
#    template:
#      src: install_zlib.sh.j2
#      dest: /tmp/install_zlib.sh
#      mode: 0755
#    tags:
#      - install_zlib
#
#  - name: install zlib, install
#    shell: . /tmp/install_zlib.sh
#    tags:
#      - install_zlib
#
#  - name: install nginx
#    shell: "cd {{nginx_src_dir}}/nginx-{{nginx_version}} && ./configure --sbin-path={{nginx_install_dir}}/nginx --conf-path={{nginx_install_dir}}/nginx.conf --pid-path={{nginx_install_dir}}/nginx.pid --with-http_ssl_module --with-pcre={{nginx_src_dir}}/pcre-{{pcre_version}} --with-zlib={{nginx_src_dir}}/zlib-{{zlib_version}} --with-openssl={{nginx_src_dir}}/openssl-{{openssl_version}} --add-module={{nginx_src_dir}}/headers-more-nginx-module-{{header_version}} && make && make install" 
#    tags:
#      - install_nginx1

  - name: install nginx
    shell: "cd {{nginx_src_dir}}/nginx-{{nginx_version}} && ./configure --sbin-path={{nginx_install_dir}}/nginx --conf-path={{nginx_install_dir}}/nginx.conf --pid-path={{nginx_install_dir}}/nginx.pid --with-http_ssl_module --with-pcre={{nginx_src_dir}}/pcre-{{pcre_version}} --with-openssl={{nginx_src_dir}}/openssl-{{openssl_version}} --add-module={{nginx_src_dir}}/headers-more-nginx-module-{{header_version}} && make && make install" 
    tags:
      - install_nginx

  - name: nginx service config
    template:
      src: nginx.j2
      dest: /etc/init.d/nginx
      mode: 0755
    tags:
      - nginx_start
