---

  - name:  Add user to server and assign full access control on / vhost.
    rabbitmq_user:
      user: "{{ rabbitmq_user }}"
      password: "{{ rabbitmq_passwd }}"
      vhost: /
      configure_priv: .*
      read_priv: .*
      write_priv: .*
      state: present
