---
  - name: install python-pip
    apt:
      name: python-pip
      state: present

  - name: install Python-dev
    apt:
      name: python-dev
      state: present

  - name: install libmysqld-dev
    apt:
      name: libmysqld-dev
      state: present

  - name: pip install MySQL-python
    shell: pip install MySQL-python
